### ISSUE TITLE
Correctie

### ISSUE THREAD

**Issue by MartineRDW** [MinBZK/Handleiding-hWho#5]
In 8.2.1 wordt Rijksdienst voor Wegverkeer (RDW) genoemd.
RDW is al sinds 1 januari 1996 een ZBO, en geen rijksdienst meer. De afkorting RDW is gebleven maar de uitgeschreven naam is Dienst Wegverkeer.

Graag aanpassen.

**Comment by PaulSBZK** [comment]
Aangepast en klaar om mee te nemen in nieuwe publicatie.
